CREATE OR REPLACE VIEW public.combine_relation_edgeview AS		
SELECT 'sales_order' || ':' ||cast(sales_order.order_id as text) AS from_id,'product_type' || ':' ||cast(sales_order.product_type_id as text) AS to_id,'quantity'||':'||cast(sales_order.quantity as text) AS predicate FROM sales_order	UNION 	SELECT 'product_type' || ':' ||cast(sales_order.product_type_id as text) AS from_id,'sales_order' || ':' ||cast(sales_order.order_id as text) AS to_id,'quantity'||':'||cast(sales_order.quantity as text) AS predicate FROM sales_order
UNION 		
SELECT 'sales_order' || ':' ||cast(sales_order.order_id as text) AS from_id,'order_type' || ':' ||cast(sales_order.order_type as text) AS to_id,'quantity'||':'||cast(sales_order.quantity as text) AS predicate FROM sales_order	UNION 	SELECT 'order_type' || ':' ||cast(sales_order.order_type as text) AS from_id,'sales_order' || ':' ||cast(sales_order.order_id as text) AS to_id,'quantity'||':'||cast(sales_order.quantity as text) AS predicate FROM sales_order
UNION 		
SELECT 'sales_order' || ':' ||cast(sales_order.order_id as text) AS from_id,'customer' || ':' ||cast(sales_order.customer_id as text) AS to_id,'quantity'||':'||cast(sales_order.quantity as text) AS predicate FROM sales_order	UNION 	SELECT 'customer' || ':' ||cast(sales_order.customer_id as text) AS from_id,'sales_order' || ':' ||cast(sales_order.order_id as text) AS to_id,'quantity'||':'||cast(sales_order.quantity as text) AS predicate FROM sales_order
UNION 		
SELECT 'sales_order' || ':' ||cast(sales_order.order_id as text) AS from_id,'product_type' || ':' ||cast(sales_order.product_type_id as text) AS to_id,'quantity'||':'||cast(sales_order.quantity as text) AS predicate FROM sales_order	UNION 	SELECT 'product_type' || ':' ||cast(sales_order.product_type_id as text) AS from_id,'sales_order' || ':' ||cast(sales_order.order_id as text) AS to_id,'quantity'||':'||cast(sales_order.quantity as text) AS predicate FROM sales_order
UNION 		
SELECT 'sales_order_shipto_address' || ':' ||cast(sales_order_shipto_address.id as text) AS from_id,'sales_order' || ':' ||cast(sales_order_shipto_address.order_id as text) AS to_id,'quantity'||':'||cast(sales_order_shipto_address.quantity as text) AS predicate FROM sales_order_shipto_address	UNION 	SELECT 'sales_order' || ':' ||cast(sales_order_shipto_address.order_id as text) AS from_id,'sales_order_shipto_address' || ':' ||cast(sales_order_shipto_address.id as text) AS to_id,'quantity'||':'||cast(sales_order_shipto_address.quantity as text) AS predicate FROM sales_order_shipto_address
UNION 		
SELECT 'sales_order_shipto_address' || ':' ||cast(sales_order_shipto_address.id as text) AS from_id,'address' || ':' ||cast(sales_order_shipto_address.address_id as text) AS to_id,'quantity'||':'||cast(sales_order_shipto_address.quantity as text) AS predicate FROM sales_order_shipto_address	UNION 	SELECT 'address' || ':' ||cast(sales_order_shipto_address.address_id as text) AS from_id,'sales_order_shipto_address' || ':' ||cast(sales_order_shipto_address.id as text) AS to_id,'quantity'||':'||cast(sales_order_shipto_address.quantity as text) AS predicate FROM sales_order_shipto_address
;		